name: Deploy Frontend to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: frontend
  publish:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
