name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Oder deine bevorzugte Node-Version

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v2
        with:
          path: frontend/build  # Passe den Build-Ordner an, je nachdem wie dein Build heißt

  publish:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
