name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run build  # falls du ein Build Script hast

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./frontend  # Pfad zu deinen gebauten Dateien (z.B. build/ oder dist/)

  publish:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
